eStream/Controllers/ChartController.cs
using eStream.Common.CommonClass;
using eStream.Models;
using Model;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using eStream.Common.CommonObject;
using eStream.Helpers.Filter;

namespace eStream.Controllers
{
    public class ChartController : BaseController
    {
        private readonly Entities _context = new Entities();
        // GET: SendSmsHis
        [BreadCrumb(ControllerName = "Biểu đồ hoạt động", AreaName = "")]
        public ActionResult Index()
        {
            PrepareDataSearch(_context);
            List<SelectListItem> listReportType = new List<SelectListItem>();
            listReportType.Add(new SelectListItem { Value = "" + GlobalConstant.REPORT_TYPE_DAY, Text = "Theo ngày" });
            listReportType.Add(new SelectListItem { Value = "" + GlobalConstant.REPORT_TYPE_MONTH, Text = "Theo tháng" });
            listReportType.Add(new SelectListItem { Value = "" + GlobalConstant.REPORT_TYPE_YEAR, Text = "Theo năm" });
            ViewData["listReportType"] = listReportType;
            return View();
        }
        public JsonResult LoadDevice(int? UnitID = null)
        {
            UserInfoBO user = SessionManager.GetUserInfoBO();
            var query = from d in _context.Device
                        where d.Status == GlobalConstant.IS_ACTIVE
                        select d;
            string sUnitID = "/" + user.UnitID + "/";
            string sUnitSearchID = "/" + UnitID.GetValueOrDefault() + "/";
            if (UnitID == null || UnitID == 0)
            {
                query = query.Where(o => (o.UnitID == null && user.IsSupperAdmin == GlobalConstant.IS_ACTIVE)
                        || _context.Unit.Any(u => u.Status == GlobalConstant.IS_ACTIVE
                        && u.UnitID == o.UnitID && u.UnitPath.Contains(sUnitID)));
            }
            else
            {
                query = query.Where(o => _context.Unit.Any(u => u.Status == GlobalConstant.IS_ACTIVE
                        && u.UnitID == o.UnitID
                        && (user.IsSupperAdmin == GlobalConstant.IS_ACTIVE || u.UnitPath.Contains(sUnitID))
                        && u.UnitPath.Contains(sUnitSearchID)));
            }
            var listDevice = query.Select(x => new DeviceModel
            {
                UnitID = x.UnitID,
                DeviceID = x.DeviceID,
                DeviceName = x.DeviceCode
            }).OrderBy(x => x.UnitID).ThenBy(x => x.DeviceName).ToList();

            return Json(listDevice, JsonRequestBehavior.AllowGet);
        }

        public JsonResult LoadChart(int DeviceID, int ReportType, DateTime FromDate)
        {
            DateTime ToDate;
            if (ReportType == GlobalConstant.REPORT_TYPE_DAY)
            {
                FromDate = FromDate.StartOfWeek(DayOfWeek.Monday);
                ToDate = FromDate.AddDays(7);
            }
            else
            {
                int year = FromDate.Year;
                FromDate = new DateTime(year, 1, 1);
                if (ReportType == GlobalConstant.REPORT_TYPE_MONTH)
                {
                    ToDate = FromDate.AddYears(1);
                }
                else
                {
                    ToDate = FromDate.AddYears(5);
                }
            }
            var iQuery = _context.DevicePlayingTime.Where(x => x.DeviceID == DeviceID && x.LogDate >= FromDate && x.LogDate < ToDate);

            List<ChartBO> listData = new List<ChartBO>();
            if (ReportType == GlobalConstant.REPORT_TYPE_DAY)
            {
                for (int i = 0; i < 7; i++)
                {
                    DateTime nextDate = FromDate.AddDays(i);
                    listData.Add(new ChartBO
                    {
                        Label = GlobalCommon.GetNameOfDay(i + 1),
                        LabelValue = nextDate.ToString("dMyyyy")
                    });
                }
                var times = iQuery.GroupBy(x => new { x.Year, x.Month, x.Date })
                    .Select(x => new
                    {
                        Value = x.Sum(s => s.TotalMinus),
                        LabelValue = x.Key.Date + "" + x.Key.Month + "" + x.Key.Year
                    }).ToList();
                foreach (var t in times)
                {
                    ChartBO c = listData.Where(x => x.LabelValue.Equals(t.LabelValue)).FirstOrDefault();
                    c.Value = Math.Round(t.Value.GetValueOrDefault() / 60, 1);
                }
            }
            else if (ReportType == GlobalConstant.REPORT_TYPE_MONTH)
            {
                for (int i = 1; i < 13; i++)
                {
                    listData.Add(new ChartBO
                    {
                        Label = "Tháng " + i,
                        LabelValue = i + "" + FromDate.Year
                    });
                }
                var times = iQuery.GroupBy(x => new { x.Year, x.Month })
                    .Select(x => new
                    {
                        Value = x.Sum(s => s.TotalMinus),
                        LabelValue = x.Key.Month + "" + x.Key.Year
                    }).ToList();
                foreach (var t in times)
                {
                    ChartBO c = listData.Where(x => x.LabelValue.Equals(t.LabelValue)).FirstOrDefault();
                    c.Value = Math.Round(t.Value.GetValueOrDefault() / 60, 1);
                }
            }
            else if (ReportType == GlobalConstant.REPORT_TYPE_YEAR)
            {
                for (int i = 0; i < 5; i++)
                {
                    listData.Add(new ChartBO
                    {
                        Label = "Năm " + (i + FromDate.Year),
                        LabelValue = "" + (i + FromDate.Year)
                    });
                }
                var times = iQuery.GroupBy(x => new { x.Year })
                    .Select(x => new
                    {
                        Value = x.Sum(s => s.TotalMinus),
                        LabelValue = "" + x.Key.Year
                    }).ToList();
                foreach (var t in times)
                {
                    ChartBO c = listData.Where(x => x.LabelValue.Equals(t.LabelValue)).FirstOrDefault();
                    c.Value = Math.Round(t.Value.GetValueOrDefault() / 60, 1);
                }
            }
            return Json(listData, JsonRequestBehavior.AllowGet);
        }

        public JsonResult LoadChartFm(int DeviceID, int ReportType, DateTime FromDate)
        {
            DateTime ToDate;
            if (ReportType == GlobalConstant.REPORT_TYPE_DAY)
            {
                FromDate = FromDate.StartOfWeek(DayOfWeek.Monday);
                ToDate = FromDate.AddDays(7);
            }
            else
            {
                int year = FromDate.Year;
                FromDate = new DateTime(year, 1, 1);
                if (ReportType == GlobalConstant.REPORT_TYPE_MONTH)
                {
                    ToDate = FromDate.AddYears(1);
                }
                else
                {
                    ToDate = FromDate.AddYears(5);
                }
            }
            var iQuery = _context.DevicePlayingFmTime.Where(x => x.DeviceID == DeviceID && x.LogDate >= FromDate && x.LogDate < ToDate);

            List<ChartBO> listData = new List<ChartBO>();
            if (ReportType == GlobalConstant.REPORT_TYPE_DAY)
            {
                for (int i = 0; i < 7; i++)
                {
                    DateTime nextDate = FromDate.AddDays(i);
                    listData.Add(new ChartBO
                    {
                        Label = GlobalCommon.GetNameOfDay(i + 1),
                        LabelValue = nextDate.ToString("dMyyyy")
                    });
                }
                var times = iQuery.GroupBy(x => new { x.Year, x.Month, x.Date })
                    .Select(x => new
                    {
                        Value = x.Sum(s => s.TotalMinus),
                        LabelValue = x.Key.Date + "" + x.Key.Month + "" + x.Key.Year
                    }).ToList();
                foreach (var t in times)
                {
                    ChartBO c = listData.Where(x => x.LabelValue.Equals(t.LabelValue)).FirstOrDefault();
                    c.Value = Math.Round(t.Value.GetValueOrDefault() / 60, 1);
                }
            }
            else if (ReportType == GlobalConstant.REPORT_TYPE_MONTH)
            {
                for (int i = 1; i < 13; i++)
                {
                    listData.Add(new ChartBO
                    {
                        Label = "Tháng " + i,
                        LabelValue = i + "" + FromDate.Year
                    });
                }
                var times = iQuery.GroupBy(x => new { x.Year, x.Month })
                    .Select(x => new
                    {
                        Value = x.Sum(s => s.TotalMinus),
                        LabelValue = x.Key.Month + "" + x.Key.Year
                    }).ToList();
                foreach (var t in times)
                {
                    ChartBO c = listData.Where(x => x.LabelValue.Equals(t.LabelValue)).FirstOrDefault();
                    c.Value = Math.Round(t.Value.GetValueOrDefault() / 60, 1);
                }
            }
            else if (ReportType == GlobalConstant.REPORT_TYPE_YEAR)
            {
                for (int i = 0; i < 5; i++)
                {
                    listData.Add(new ChartBO
                    {
                        Label = "Năm " + (i + FromDate.Year),
                        LabelValue = "" + (i + FromDate.Year)
                    });
                }
                var times = iQuery.GroupBy(x => new { x.Year })
                    .Select(x => new
                    {
                        Value = x.Sum(s => s.TotalMinus),
                        LabelValue = "" + x.Key.Year
                    }).ToList();

eStream/Views/Manager/_Chart.cshtml
@using eStream.Common.CommonClass
@using eStream.Common.CommonObject
@using Model;
@using eStream.Models
@{
    string chartTitle = ViewData["ChartTitle"] as string;
    DateTime FromDate = (ViewData["FromDate"] as DateTime?).Value;
    int reportType = (ViewData["ReportType"] as int?).GetValueOrDefault();
    DateTime now = DateTime.Now;
}

@model DeviceModel
<div class="modal-dialog modal-lg">
    <div class="modal-content">
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal">&times;</button>
            <h4 class="modal-title">Biểu đồ thời gian hoạt động của thiết bị @Model.DeviceName</h4>
        </div>
        <div class="modal-body">
            <div class="row">
                <div class="col-md-2"></div>
                <div class="col-md-8 text-center">
                    <button class="btn btn-default pull-left" onclick="viewChart(@Model.DeviceID, '@FromDate' , -1)"><i class="fa fa-lg fa-angle-left"></i></button>
                    
                    @if (reportType == GlobalConstant.REPORT_TYPE_DAY)
                    {
                        <button class="btn btn-primary" id="btnDay" onclick="setReportType(this, @GlobalConstant.REPORT_TYPE_DAY)">Thống kê ngày</button>
                    }
                    else
                    {
                        <button class="btn btn-default" id="btnDay" onclick="setReportType(this, @GlobalConstant.REPORT_TYPE_DAY)">Thống kê ngày</button>
                    }
                    @if (reportType == GlobalConstant.REPORT_TYPE_MONTH)
                    {
                        <button class="btn btn-primary" id="btnMonth" onclick="setReportType(this, @GlobalConstant.REPORT_TYPE_MONTH)">Thống kê tháng</button>
                    }
                    else
                    {
                        <button class="btn btn-default" id="btnMonth" onclick="setReportType(this, @GlobalConstant.REPORT_TYPE_MONTH)">Thống kê tháng</button>
                    }
                    @if (reportType == GlobalConstant.REPORT_TYPE_YEAR)
                    {
                        <button class="btn btn-primary" id="btnYear" onclick="setReportType(this, @GlobalConstant.REPORT_TYPE_YEAR)">Thống kê năm</button>
                    }
                    else
                    {
                        <button class="btn btn-default" id="btnYear" onclick="setReportType(this, @GlobalConstant.REPORT_TYPE_YEAR)">Thống kê năm</button>
                    }
                    
                    <input type="hidden" id="ReportType" name="ReportType" value="@reportType" />
                    <button class="btn btn-default pull-right" onclick="viewChart(@Model.DeviceID, '@FromDate' , 1)"><i class="fa fa-lg fa-angle-right"></i></button>
                </div>
                <div class="col-md-2"></div>
            </div>
            <br />
            <div class="row">
                <div class="col-md-12">
                    <canvas id="barChart" height="420" width="800"></canvas>
                </div>
            </div>
        </div>
    </div>
</div>
<script type="text/javascript">
    $(document).ready(function () {
        loadChart(@Model.DeviceID, '@FromDate');
    });

    function loadChart(id, fromDate){
        var reportType = $("#ReportType").val();
        $.ajax({
            type: "POST",
            url: '@Url.Action("LoadChart", "Chart")',
            data: {"DeviceID" : id, "FromDate": fromDate, "ReportType": reportType},
            success: function (data) {
                setTimeout(function(){ genChart(data, '@chartTitle'); }, 200);
            },
            error: function (xhr) {
                CommonJS.alert(xhr.responseText, false);
            }
        });
    }

    function setReportType(btn, reportType) {
        $("#ReportType").val(reportType);
        $("#btnDay").attr("class", "btn btn-default");
        $("#btnMonth").attr("class", "btn btn-default");
        $("#btnYear").attr("class", "btn btn-default");
        $(btn).attr("class", "btn btn-primary");
        viewChart(@Model.DeviceID, '@now', 0);
    }

    function onFail(xhr) {
        CommonJS.alert(xhr.responseText);
    }
</script>

eStream/Views/Manager/_Config.cshtml
@using eStream.Models
@using eStream.Common.CommonClass
@model DeviceModel
@{
    var user = SessionManager.GetUserInfoBO();
    List<SelectListItem> listBitrate = ViewData["listBitrate"] as List<SelectListItem>;
}
@using (Ajax.BeginForm("SaveConfig", "Manager", new AjaxOptions()
{
    HttpMethod = "post",
    OnBegin = "onBegin",
    OnSuccess = "onSuccess",
    OnFailure = "onFail"
}, new { id = "frmCreateOrEdit" }))
{
    @Html.AntiForgeryToken()
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                @Html.HiddenFor(model => model.DeviceID)
                @Html.HiddenFor(model => model.UnitID)
                <h4 class="modal-title">Cấu hình thiết bị cho: @Model.DeviceName</h4>
            </div>
            <div class="modal-body">
                <div class="form-horizontal">
                    <div class="form-group">
                        <label class="col-md-2 control-label">Bitrate</label>
                        <div class="col-md-4">
                            @Html.DropDownListFor(x => x.Bitrate, listBitrate, new { @class = "form-control chosen-select", style = "width: 100%" })
                        </div>
                        <label class="col-md-2 control-label">Âm lượng</label>
                        <div class="col-md-4">
                            @Html.TextBoxFor(x => x.Volume, new { @class = "form-control" })
                            @Html.ValidationMessageFor(x => x.Volume)
                        </div>
                    </div>
                    <div class="form-group">
                        @if (user.IsSupperAdmin == GlobalConstant.IS_ACTIVE || user.IsAdmin == GlobalConstant.IS_ACTIVE)
                        {
                            <label class="col-md-2 control-label"></label>
                            <div class="col-md-4">
                                <div class="i-checks"><label>@Html.CheckBoxFor(x => x.IsSupportFm) Thu được FM</label></div>
                            </div>
                        }
                    </div>
                    @if (user.IsSupperAdmin == GlobalConstant.IS_ACTIVE)
                    {
                        <div class="form-group">
                            <label class="col-md-2 control-label"></label>
                            <div class="col-md-4">
                                <div class="i-checks"><label>@Html.CheckBoxFor(x => x.IsSMS) Gửi tin nhắn SMS</label></div>
                            </div>
                            <label class="col-md-2 control-label">Thời gian đồng bộ</label>
                            <div class="col-md-4">
                                <div class="input-group">
                                    @Html.TextBoxFor(x => x.SyncTime, new { @class = "form-control" })
                                    <div class="input-group-addon"><i class="fa fa-clock-o"></i> Giây/Lần</div>
                                </div>
                                @Html.ValidationMessageFor(x => x.SyncTime)
                            </div>
                        </div>
                    }
                    <div class="form-group">
                        <label class="col-md-2 control-label"></label>
                        <div class="col-md-4">
                            <div class="i-checks"><label>@Html.RadioButtonFor(x => x.NoVov, GlobalConstant.IS_NOT_ACTIVE) Chuyển tiếp VOV</label></div>
                        </div>
                        <label class="col-md-2 control-label"></label>
                        <div class="col-md-4">
                            <div class="i-checks"><label>@Html.RadioButtonFor(x => x.NoVov, GlobalConstant.IS_ACTIVE) Không chuyển tiếp VOV</label></div>
                        </div>
                    </div>
                    @if (!string.IsNullOrWhiteSpace(Model.DeviceExt.ConnMod))
                    {
                        <div class="form-group">
                            <label class="col-md-2 control-label">Loại kết nối</label>
                            <div class="col-md-3">
                                <div class="i-checks"><label>@Html.RadioButtonFor(x => x.ConnType, GlobalConstant.CONN_TYPE_3G) 3G</label></div>
                            </div>
                            <div class="col-md-3">
                                <div class="i-checks"><label>@Html.RadioButtonFor(x => x.ConnType, GlobalConstant.CONN_TYPE_4G) 4G</label></div>
                            </div>
                            <div class="col-md-3">
                                <div class="i-checks"><label>@Html.RadioButtonFor(x => x.ConnType, GlobalConstant.CONN_TYPE_AUTO) AUTO</label></div>
                            </div>
                        </div>
                    }
                </div>
            </div>
            <div class="modal-footer">
                <button type="submit" class="btn btn-success"><i class="fa fa-floppy-o"></i> Lưu</button>
                <button type="button" data-dismiss="modal" class="btn btn-default"><i class="fa fa-ban"></i> Hủy</button>
            </div>
        </div>
    </div>
}
<script type="text/javascript">
    $(document).ready(function () {
        $("select").chosen({ width: "100%" });
        $.validator.unobtrusive.parse("#frmCreateOrEdit");
        $('.i-checks').iCheck({
            checkboxClass: 'icheckbox_square-green',
            radioClass: 'iradio_square-green',
        });
    });

    function onBegin() {
        if ($("#frmCreateOrEdit").valid()) {
            return true;
        } else {
            return false;
        }
    }

    function onSuccess(msg) {
        CommonJS.alert(msg);
        $("#modal-log").modal("toggle");
    }

    function onFail(xhr) {
        CommonJS.alert(xhr.responseText);
    }
</script>

eStream/Views/Manager/_Info.cshtml
@using eStream.Models
@using eStream.Common.CommonClass;
@model DeviceModel
<div class="modal-dialog modal-lg">
    <div class="modal-content">
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal">&times;</button>
            <h4 class="modal-title">Thông tin thiết bị</h4>
        </div>
        <div class="modal-body">
            <div class="form-horizontal">
                <div class="row">
                    <div class="col-md-6">
                        <div class="form-group">
                            <label class="col-md-5">Tên thiết bị:</label>
                            <div class="col-md-7">@Model.DeviceName</div>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="form-group">
                            <label class="col-md-5">Mã thiết bị:</label>
                            <div class="col-md-7">@Model.SDeviceCode</div>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-6">
                        <div class="form-group">
                            <label class="col-md-5">Xã/Phường:</label>
                            <div class="col-md-7">@Model.CommuneName</div>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="form-group">
                            <label class="col-md-5">Huyện/Thành phố:</label>
                            <div class="col-md-7">@Model.DistrictName</div>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-6">
                        <div class="form-group">
                            <label class="col-md-5">Người quản lý:</label>
                            <div class="col-md-7">@Model.ManagerName</div>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="form-group">
                            <label class="col-md-5">SĐT người quản lý:</label>
                            <div class="col-md-7"><a href="tel:@Model.ManagerPhone">@Model.ManagerPhone</a></div>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-6">
                        <div class="form-group">
                            <label class="col-md-5">Số thuê bao:</label>
                            <div class="col-md-7">@Model.SimNumber</div>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="form-group">
                            <label class="col-md-5">Trạng thái:</label>
                            <div class="col-md-7">
                                @if (Model.Status == GlobalConstant.DEVICE_STATUS_READY)
                                {
                                    <span class="label label-primary">Sẵn sàng</span>
                                }
                                else if (Model.Status == GlobalConstant.DEVICE_STATUS_BEAK)
                                {
                                    <span class="label label-danger">Hỏng</span>
                                }
                                else if (Model.Status == GlobalConstant.DEVICE_STATUS_GUARANT)
                                {
                                    <span class="label label-warning">Bảo hành</span>
                                }
                            </div>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-6">
                        <div class="form-group">
                            <label class="col-md-5">Âm lượng:</label>
                            <div class="col-md-7">@Model.Volume%</div>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="form-group">
                            <label class="col-md-5">Chất lượng âm thanh:</label>
                            <div class="col-md-7">@Model.Bitrate kbps</div>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-6">
                        <div class="form-group">
                            <label class="col-md-5">Thời gian đồng bộ:</label>
                            <div class="col-md-7">@Model.SyncTime (s/lần)</div>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="form-group">
                            <label class="col-md-5">Gửi tin nhắn:</label>
                            <div class="col-md-7">
                                @if (Model.IsSMS)
                                {
                                    <span class="label label-primary">Có gửi</span>
                                }
                                else
                                {
                                    <span class="label label-warning">Không gửi</span>
                                }
                            </div>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-6">
                        <div class="form-group">
                            <label class="col-md-5">Dung lượng bộ nhớ:</label>
                            <div class="col-md-7">@Model.DeviceExt.RamTotal</div>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="form-group">
                            <label class="col-md-5">Bộ nhớ đã sử dụng:</label>
                            <div class="col-md-7">@Model.DeviceExt.RamUsage</div>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-6">
                        <div class="form-group">
                            <label class="col-md-5">Mạng:</label>
                            <div class="col-md-7">
                                <div class="@Model.DeviceExt.Display.ClassDis"></div>@Model.DeviceExt.Display.TextDis
                            </div>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="form-group">
                            <label class="col-md-5">Tốc độ CPU:</label>
                            <div class="col-md-7">@Model.DeviceExt.CpuFreq</div>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-6">
                        <div class="form-group">
                            <label class="col-md-5">Nhiệt độ CPU:</label>
                            <div class="col-md-7">@Model.DeviceExt.CpuTemp</div>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="form-group">
                            <label class="col-md-5">Sử dụng CPU:</label>
                            <div class="col-md-7">@Model.DeviceExt.CpuUsage</div>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-6">
                        <div class="form-group">
                            <label class="col-md-5">Serial SIM:</label>
                            <div class="col-md-7">@Model.SimSer</div>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="form-group">
                            <label class="col-md-5">Phiên bản firmware:</label>
                            <div class="col-md-7">@Model.Version</div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="modal-footer">
            <button type="button" data-dismiss="modal" class="btn btn-default"><i class="fa fa-ban"></i> Hủy</button>
        </div>
    </div>
</div>

eStream/Views/Manager/_LstLog.cshtml
@using eStream.Common.CommonClass;
@using eStream.Models;
@using PagedList;
@using PagedList.Mvc;
@{
    PagedList<DeviceLogModel> paginate = ViewData["listLog"] as PagedList<DeviceLogModel>;
    var grid = new WebGrid(
                          rowsPerPage: paginate.PageSize,
                          canPage: true,
                          canSort: false,
                          ajaxUpdateContainerId: "gridLog"
                          );

    grid.Bind(paginate,
    autoSortAndPage: false,
    rowCount: paginate.Count);
}
@if (paginate.Count > 0)
{
    var gridColumns = new List<WebGridColumn>();
    gridColumns.Add(grid.Column("LogID", "LogID"));
    gridColumns.Add(grid.Column("MessageDetail", "Tên hành động"));
    gridColumns.Add(grid.Column("LogDate", "Thời gian gửi", format: (x) => x.LogDate == null ? "" : string.Format("{0:dd/MM/yyyy HH:mm:ss}", x.LogDate)));
    gridColumns.Add(grid.Column("Status", "Trạng thái", format: @<text>
        @if (item.Status != null && item.Status == true)
        {
            <span class="label label-primary">Thành công</span>
        }
        else
        {
            <span class="label label-danger">Thất bại</span>
        }
    </text>));
    @grid.GetHtml(htmlAttributes: new { id = "gridLog" },
                                   fillEmptyRows: false,
                                   tableStyle: "table table-striped table-hover",
                                   alternatingRowStyle: "altRow",
                                   selectedRowStyle: "selectRow",
                                   columns: gridColumns)
    <div class="pagination">
        @Html.PagedListPager(paginate, page => Url.Action("SearchLog",
                                   new
                                   {
                                       DeviceID = ViewBag.DeviceID,
                                       FromDate = ViewBag.FromDate,
                                       ToDate = ViewBag.ToDate,
                                       LogType = ViewBag.LogType,
                                       page,
                                       pageSize = paginate.PageSize

                                   }), PagedListRenderOptions.EnableUnobtrusiveAjaxReplacing(new AjaxOptions() { HttpMethod = "GET", UpdateTargetId = "divDetailLog" }))
    </div>
}
else
{
    <div style="color:red; margin-left:10px;">
        Không có dữ liệu
    </div>
}

eStream/Views/Manager/_LstSms.cshtml
@using eStream.Common.CommonClass;
@using eStream.Models;
@using PagedList;
@using PagedList.Mvc;
@{
    string sms = ViewData["sms"] as string;
}
@if (!string.IsNullOrWhiteSpace(sms))
{
    <textarea style="height: 450px" readonly class="trans">@sms</textarea>
}
else
{
    <div style="color:red; margin-left:10px;">
        Không có dữ liệu
    </div>
}