eStream/Controllers/ConfigController.cs
using eStream.Common.CommonObject;
using eStream.Common.CommonClass;
using eStream.Helpers.Filter;
using eStream.Models;
using Model;
using PagedList;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace eStream.Controllers
{
    public class ConfigController : Controller
    {
        private readonly Entities _context = new Entities();
        //
        // GET: /Unit/
        [BreadCrumb(ControllerName = "Cấu hình hệ thống", ActionName = "Cấu hình", AreaName = "Quản trị hệ thống")]
        public ActionResult Index()
        {
            var config = _context.SystemConfig.FirstOrDefault();
            var model = new SystemConfigModel
            {
                IsUseOTP = config.IsUseOTP.GetValueOrDefault() == GlobalConstant.IS_ACTIVE,
                ExpOTP = config.ExpOTP
            };
            return View(model);
        }

        public int GetUnitType(OrderConfig config, int orderNumber)
        {
            if (orderNumber == config.VillageOrder)
            {
                return GlobalConstant.UNIT_TYPE_VILLAGE;
            }
            if (orderNumber == config.CommuneOrder)
            {
                return GlobalConstant.UNIT_TYPE_COMMUNE;
            }
            if (orderNumber == config.DistrictOrder)
            {
                return GlobalConstant.UNIT_TYPE_DISTRICT;
            }
            if (orderNumber == config.ProvinceOrder)
            {
                return GlobalConstant.UNIT_TYPE_PROVINCE;
            }
            return 0;
        }

        public int GetOrder(OrderConfig config, int unitType)
        {
            if (unitType == GlobalConstant.UNIT_TYPE_VILLAGE)
            {
                return config.VillageOrder;
            }
            if (unitType == GlobalConstant.UNIT_TYPE_COMMUNE)
            {
                return config.CommuneOrder;
            }
            if (unitType == GlobalConstant.UNIT_TYPE_DISTRICT)
            {
                return config.DistrictOrder;
            }
            if (unitType == GlobalConstant.UNIT_TYPE_PROVINCE)
            {
                return config.ProvinceOrder;
            }
            return 0;
        }
        public void UpdateOrder(OrderConfig config, int unitType, int orderNumber)
        {
            if (unitType == GlobalConstant.UNIT_TYPE_VILLAGE)
            {
                config.VillageOrder = orderNumber;
            }
            if (unitType == GlobalConstant.UNIT_TYPE_COMMUNE)
            {
                config.CommuneOrder = orderNumber;
            }
            if (unitType == GlobalConstant.UNIT_TYPE_DISTRICT)
            {
                config.DistrictOrder = orderNumber;
            }
            if (unitType == GlobalConstant.UNIT_TYPE_PROVINCE)
            {
                config.ProvinceOrder = orderNumber;
            }
        }

        public PartialViewResult LoadUnitOrder()
        {
            UserInfoBO user = SessionManager.GetUserInfoBO();
            if (user.IsSupperAdmin.GetValueOrDefault() == 0)
            {
                throw new BusinessException("Bạn không có quyền thực hiện thao tác này");
            }
            var config = _context.OrderConfig.FirstOrDefault();
            if (config == null)
            {
                config = new OrderConfig
                {
                    VillageOrder = 1,
                    CommuneOrder = 2,
                    DistrictOrder = 3,
                    ProvinceOrder = 4
                };
                _context.OrderConfig.Add(config);
                _context.SaveChanges();
            }
            List<UnitOrderModel> listUnitOrder = new List<UnitOrderModel>();
            listUnitOrder.Add(new UnitOrderModel
            {
                NumberOrder = 1,
                UnitType = GetUnitType(config, 1)
            });
            listUnitOrder.Add(new UnitOrderModel
            {
                NumberOrder = 2,
                UnitType = GetUnitType(config, 2)
            });
            listUnitOrder.Add(new UnitOrderModel
            {
                NumberOrder = 3,
                UnitType = GetUnitType(config, 3)
            });
            listUnitOrder.Add(new UnitOrderModel
            {
                NumberOrder = 4,
                UnitType = GetUnitType(config, 4)
            });
            ViewData["listUnitOrder"] = listUnitOrder;
            return PartialView("_ListUnitOrder");
        }

        [HttpPost]
        public JsonResult Move(int unitType, int step)
        {
            var config = _context.OrderConfig.FirstOrDefault();
            int currentOrder = GetOrder(config, unitType);
            int nextOrder = currentOrder;
            currentOrder -= step;
            int nextUnitType = GetUnitType(config, currentOrder);
            UpdateOrder(config, unitType, currentOrder);
            UpdateOrder(config, nextUnitType, nextOrder);
            _context.SaveChanges();
            return Json("Sắp xếp thứ tự phát thành công", JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public JsonResult SaveConfig(SystemConfigModel model)
        {
            var config = _context.SystemConfig.FirstOrDefault();
            model.UpdateEntity(config);
            _context.SaveChanges();
            ConfigCaching.LoadCaching();
            return Json("Lưu cấu hình thành công", JsonRequestBehavior.AllowGet);
        }

        [SkipDomainHashFilterAttribute]
        [AllowAnonymous]
        [SkipActionLogFilter]
        public JsonResult Hash256(string text)
        {
            if (string.IsNullOrWhiteSpace(text))
            {
                text = string.Empty;
            }
            var path = System.IO.Path.GetDirectoryName(System.Reflection.Assembly.GetExecutingAssembly().GetName().CodeBase).Substring(6);
            var toolPath = System.IO.Path.Combine(path, "Tool.dll");
            System.Reflection.Assembly assembly = System.Reflection.Assembly.LoadFrom(toolPath);
            Type type = assembly.GetType("Tool.Crypto");
            object cryptoTool = Activator.CreateInstance(type);
            string methodName = "ComputeSha256Hash";
            System.Reflection.MethodInfo methodInfo = type.GetMethod(methodName);
            var parameters = new List<object>() { text, GlobalConstant.VERY_SECRET + GlobalConstant.DOMAIN_SECRET };
            var response = methodInfo.Invoke(cryptoTool, parameters.ToArray());
            return Json(new { Message = response }, JsonRequestBehavior.AllowGet);
        }

        [SkipDomainHashFilterAttribute]
        [AllowAnonymous]
        [SkipActionLogFilter]
        public JsonResult Encrypt(string text)
        {
            if (string.IsNullOrWhiteSpace(text))
            {
                text = string.Empty;
            }
            var path = System.IO.Path.GetDirectoryName(System.Reflection.Assembly.GetExecutingAssembly().GetName().CodeBase).Substring(6);
            var toolPath = System.IO.Path.Combine(path, "Tool.dll");
            System.Reflection.Assembly assembly = System.Reflection.Assembly.LoadFrom(toolPath);
            Type type = assembly.GetType("Tool.Crypto");
            object cryptoTool = Activator.CreateInstance(type);
            string methodName = "EncryptString";
            System.Reflection.MethodInfo methodInfo = type.GetMethod(methodName);
            var parameters = new List<object>() { text, GlobalConstant.SECRET };
            var response = methodInfo.Invoke(cryptoTool, parameters.ToArray());
            return Json(new { Message = response }, JsonRequestBehavior.AllowGet);
        }

        [SkipDomainHashFilterAttribute]
        [AllowAnonymous]
        [SkipActionLogFilter]
        public JsonResult Decrypt(string text)
        {
            if (string.IsNullOrWhiteSpace(text))
            {
                text = string.Empty;
            }
            var path = System.IO.Path.GetDirectoryName(System.Reflection.Assembly.GetExecutingAssembly().GetName().CodeBase).Substring(6);
            var toolPath = System.IO.Path.Combine(path, "Tool.dll");
            System.Reflection.Assembly assembly = System.Reflection.Assembly.LoadFrom(toolPath);
            Type type = assembly.GetType("Tool.Crypto");
            object cryptoTool = Activator.CreateInstance(type);
            string methodName = "DecryptString";
            System.Reflection.MethodInfo methodInfo = type.GetMethod(methodName);
            var parameters = new List<object>() { text, GlobalConstant.SECRET };
            var response = methodInfo.Invoke(cryptoTool, parameters.ToArray());
            return Json(new { Message = response }, JsonRequestBehavior.AllowGet);
        }


        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                _context.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

eStream/Controllers/DeviceConfigController.cs
using eStream.Common.CommonClass;
using eStream.Common.CommonObject;
using eStream.Helpers.Filter;
using eStream.Models;
using Model;
using PagedList;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;

namespace eStream.Controllers
{
    public class DeviceConfigController : BaseController
    {
        private  readonly Entities _context = new Entities();
        [BreadCrumb(ControllerName = "Cấu hình", ActionName = "", AreaName = "")]
        public ActionResult Index()
        {
            PrepareDataSearch(_context);
            return View();
        }

        public PartialViewResult SearchConfig(int? DistrictID, int? CommuneID, int page = 1)
        {
            UserInfoBO user = SessionManager.GetUserInfoBO();
            string sUnit = "/" + user.UnitID + "/";
            var iQConfig = _context.Unit.Where(x => x.UnitLevel == GlobalConstant.UNIT_TYPE_COMMUNE && x.UnitPath.Contains(sUnit))
                .Select(x => new UnitModel
                {
                    UnitID = x.UnitID,
                    UnitPath = x.UnitPath,
                    UnitName = x.UnitName,
                    ParentName = _context.Unit.Where(u => u.UnitID == x.ParentID).Select(u => u.UnitName).FirstOrDefault(),
                    DeviceConfigID = _context.DeviceConfig.Where(c => c.UnitID == x.UnitID).Select(c => c.DeviceConfigID).FirstOrDefault()
                }).OrderBy(x => x.UnitPath).ThenBy(x => x.UnitName);

            var listConfig = iQConfig.ToList();
            PagedList<UnitModel> paginate = new PagedList<UnitModel>(listConfig, page, GlobalConstant.PAGE_SIZE);
            ViewData["listConfig"] = paginate;
            ViewBag.DistrictID = DistrictID;
            ViewBag.CommuneID = CommuneID;
            return PartialView("_LstConfig");
        }

        public PartialViewResult OpenConfig(int unitID)
        {
            UserInfoBO user = SessionManager.GetUserInfoBO();
            string sUnit = "/" + user.UnitID + "/";
            Unit unit = _context.Unit.Where(x => x.Status == GlobalConstant.IS_ACTIVE && x.UnitLevel == GlobalConstant.UNIT_TYPE_COMMUNE
            && x.UnitID == unitID && x.UnitPath.Contains(sUnit)).FirstOrDefault();
            DeviceConfigModel model = new DeviceConfigModel();
            if (unit != null)
            {
                DeviceConfig entity = _context.DeviceConfig.Where(x => x.UnitID == unitID).FirstOrDefault();
                model.EntityTo(entity, unit);
                // cac list du lieu
                List<SelectListItem> listBitrate = new List<SelectListItem>();
                listBitrate.Add(new SelectListItem { Value = "", Text = "--Mặc định--" });
                listBitrate.Add(new SelectListItem { Value = "64", Text = "64kbps" });
                listBitrate.Add(new SelectListItem { Value = "128", Text = "128kbps" });
                listBitrate.Add(new SelectListItem { Value = "320", Text = "320kbps" });
                ViewData["listBitrate"] = listBitrate;
                return PartialView("_Config", model);
            }
            else
            {
                ViewData["noUnit"] = GlobalConstant.IS_ACTIVE;
                return PartialView("_Config", model);
            }
        }

        public JsonResult SaveConfig(DeviceConfigModel model)
        {
            UserInfoBO user = SessionManager.GetUserInfoBO();
            string sUnit = "/" + user.UnitID + "/";
            Unit unit = _context.Unit.Where(x => x.Status == GlobalConstant.IS_ACTIVE && x.UnitLevel == GlobalConstant.UNIT_TYPE_COMMUNE
            && x.UnitID == model.UnitID && x.UnitPath.Contains(sUnit)).FirstOrDefault();
            if (unit != null)
            {
                DeviceConfig entity = null;
                if (model.DeviceConfigID != null && model.DeviceConfigID > 0)
                {
                    entity = _context.DeviceConfig.Find(model.DeviceConfigID);
                    if (entity == null)
                    {
                        throw new BusinessException("Không tồn tại cấu hình vừa chọn");
                    }
                    model.UpdateEntity(entity);
                }
                else
                {
                    entity = new DeviceConfig();
                    model.UpdateEntity(entity);
                    _context.DeviceConfig.Add(entity);
                }
                // Luu thay doi cua thiet bi
                List<Device> listDevice = _context.Device.Where(x => x.UnitID == entity.UnitID).ToList();
                foreach (Device device in listDevice)
                {
                    if (device.SyncTime.GetValueOrDefault() > 0)
                    {
                        device.IsChangeSyncTime = GlobalConstant.IS_ACTIVE;
                    }
                    device.IsChangeVolume = GlobalConstant.IS_ACTIVE;
                    DeviceCommandCaching.AddCommand(device.DeviceID, GlobalConstant.DEVICE_COMMAND_CHANGE_VOLUME);
                    DeviceCommandCaching.AddCommand(device.DeviceID, GlobalConstant.DEVICE_COMMAND_CHECK_INTERVAL);
                }
                _context.SaveChanges();
                return Json("Cấu hình thành công", JsonRequestBehavior.AllowGet);
            }
            else
            {
                throw new BusinessException("Bạn không có quyền cấu hình cho xã này");
            }
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                _context.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

eStream/Views/DeviceConfig/Index.cshtml
@using eStream.Common.CommonClass
@using eStream.Common.CommonObject
@using eStream.Models
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
    UserInfoBO user = SessionManager.GetUserInfoBO();
    string unitName = string.Empty;
    int isLoadChild = 0;
    int unitID = 0;
    if (user.UnitLevel == GlobalConstant.UNIT_TYPE_PROVINCE)
    {
        isLoadChild = 1;
        List<UnitModel> listDistrict = ViewData["listDistrict"] as List<UnitModel>;
        if (listDistrict != null && listDistrict.Count > 1)
        {
            unitName = listDistrict[1].UnitName;
            unitID = listDistrict[1].UnitID;
        }
    }
    else if (user.UnitLevel == GlobalConstant.UNIT_TYPE_DISTRICT)
    {
        List<UnitModel> listCommune = ViewData["listCommune"] as List<UnitModel>;
        if (listCommune != null && listCommune.Count > 1)
        {
            unitName = listCommune[1].UnitName;
            unitID = listCommune[1].UnitID;
        }
    }
    else
    {
        List<UnitModel> listCommune = ViewData["listCommune"] as List<UnitModel>;
        unitID = listCommune[0].UnitID;
        unitName = listCommune[0].UnitName;
    }
}<div class="row" id="divIndex">
    <input type="hidden" name="UnitID" id="UnitID" value="@unitID" />
    <div class="col-lg-3">
        <div class="row">
            @if (user.UnitLevel == GlobalConstant.UNIT_TYPE_PROVINCE)
            {
                <div class="col-md-12" id="divProvince">
                    @Html.Partial("../User/_Unit", ViewData["listDistrict"])
                </div>
            }
            <div class="col-md-12" id="divDistrict">
                @Html.Partial("../User/_Unit", ViewData["listCommune"])
            </div>
        </div>
    </div>
    <div class="col-lg-9">
        <div class="row" id="divConfig">

        </div>
    </div>
</div>
 <script type="text/javascript">
    $(document).ready(function () {
        $("select").chosen({ width: "100%" });
        var isLoadChild = @isLoadChild;
        var unitID = @unitID;
        if (isLoadChild == 0) {
            var item = $("#divDistrict").find('a[val=' + unitID + ']:first');
            if (item != undefined && item != null) {
                setUnitAndSearch(item);
            }
        } else {
            loadChild(unitID);
        }
    });

    function openConfig() {
        var unitID = $("#divIndex #UnitID").val()
        $.ajax({
            type: "POST",
            url: '@Url.Action("OpenConfig", "DeviceConfig")',
            data: { "unitID": unitID },
            success: function (result) {
                $("#divConfig").html(result);
            },
            error: function (e) {
                CommonJS.alert(e.responseText);
            }
        });
    }

    function choiceUnit(item, unitName, isLoadChild) {
        var id = $(item).attr('val');
        if (id == 0) {
            return;
        }
        $('#divTitle').html("Cấu hình thiết bị " + unitName);
        if (isLoadChild != undefined && isLoadChild != null && isLoadChild == 1) {
            setActive(item);
            if (id > 0) {
                loadChild(id)
            } else {
                $("#divDistrict").html("");
            }
        } else {
            setUnitAndSearch(item);
        }
    }

    function loadChild(unitID) {
        // Load lai cay don vi
        $.ajax({
            type: "POST",
            url: '@Url.Action("LoadUnit", "User")',
            data: { "UnitID": unitID },
            success: function (data) {
                $("#divDistrict").html(data);
                var item = $("#divDistrict").find(".list-group-item:nth-child(2)");
                if (item != undefined && item != null) {
                    setUnitAndSearch(item);
                }
            },
            error: function (xhr) {
                CommonJS.alert(xhr.responseText, false);
            }
        });
    }

    function setUnitAndSearch(item) {
        var id = $(item).attr('val');
        $("#divIndex #UnitID").val(id);
        // Thiet lap active
        setActive(item);
        // Tim kiem thiet bi
        openConfig();
    }

    function setActive(item) {
        var li = $(item).parent();
        $(item).removeClass("active");
        li.find("a").each(function () {
            $(this).removeClass("active");
            var i = $(this).find("i:first");
            var iClass = i.attr('class');
            if (iClass != undefined && iClass != '') {
                i.removeClass(iClass);
                iClass = iClass.replace(/\-o/g, "");
                i.addClass(iClass);
            }
        });
        $(item).addClass("active");
        var iChild = $(item).find("i:first");
        var iChildClass = iChild.attr('class');
        if (iChildClass != undefined && iChildClass != '') {
            if (!iChildClass.endsWith("-o")) {
                iChild.removeClass(iChildClass);
                iChildClass += "-o";
                iChild.addClass(iChildClass);
            }
        }
    }
 </script>

eStream/Views/DeviceConfig/_Config.cshtml
@using eStream.Models
@model DeviceConfigModel
@{
    List<SelectListItem> listBitrate = ViewData["listBitrate"] as List<SelectListItem>;
    int noUnit = (ViewData["noUnit"] as int?).GetValueOrDefault();
}
@using (Ajax.BeginForm("SaveConfig", "DeviceConfig", new AjaxOptions()
{
    HttpMethod = "post",
    OnBegin = "onBegin",
    OnSuccess = "onSuccess",
    OnFailure = "onFail"
}, new { id = "frmCreateOrEdit" }))
{
    @Html.AntiForgeryToken()
    <div class="ibox float-e-margins">
        @if (noUnit == 1)
        {
            <div class="ibox-title">
                <h5 id="divTitle">CHỌN XÃ ĐỂ CẤU HÌNH THIẾT BỊ</h5>
            </div>
        }
        else
        {
            <div class="ibox-title">
                @Html.HiddenFor(model => model.DeviceConfigID)
                @Html.HiddenFor(model => model.UnitID)
                <h5 id="divTitle">Cấu hình thiết bị cho: @Model.UnitName</h5>
            </div>
            <div class="ibox-content">
                <div class="form-horizontal">
                    <div class="form-group">
                        <label class="col-lg-2 control-label">Bitrate</label>
                        <div class="col-lg-4">
                            @Html.DropDownListFor(x => x.BitRate, listBitrate, new { @class = "form-control chosen-select", style = "width: 100%" })
                        </div>
                        <label class="col-lg-2 control-label">Thời gian đồng bộ</label>
                        <div class="col-lg-4">
                            <div class="input-group">
                                @Html.TextBoxFor(x => x.SyncTime, new { @class = "form-control" })
                                <div class="input-group-addon"><i class="fa fa-clock-o"></i> Giây/Lần</div>
                            </div>
                            @Html.ValidationMessageFor(x => x.SyncTime)
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-lg-2 control-label">Âm lượng</label>
                        <div class="col-lg-4">
                            @Html.TextBoxFor(x => x.DefaultVolume, new { @class = "form-control" })
                            @Html.ValidationMessageFor(x => x.DefaultVolume)
                        </div>
                        <label class="col-lg-2 control-label"></label>
                        <div class="col-lg-4">
                            <div class="i-checks"><label>@Html.CheckBoxFor(x => x.IsSMS) Gửi tin nhắn SMS</label></div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="ibox-footer">
                <button type="submit" class="btn btn-success"><i class="fa fa-floppy-o"></i> Lưu</button>
            </div>
        }
    </div>
}
<script type="text/javascript">
    $(document).ready(function () {
        $("select").chosen({ width: "100%" });
        $.validator.unobtrusive.parse("#frmCreateOrEdit");
        $('.i-checks').iCheck({
            checkboxClass: 'icheckbox_square-green',
            radioClass: 'iradio_square-green',
        });
    });

    function onBegin() {
        if ($("#frmCreateOrEdit").valid()) {
            return true;
        } else {
            return false;
        }
    }

    function onSuccess(msg) {
        CommonJS.alert(msg);
        searchConfig();
    }

    function onFail(xhr) {
        CommonJS.alert(xhr.responseText);
    }
</script>

eStream/Views/DeviceConfig/_LstConfig.cshtml
@using eStream.Common.CommonClass
@using eStream.Common.CommonObject
@using eStream.Models;
@using PagedList;
@using PagedList.Mvc;
@{
    UserInfoBO user = SessionManager.GetUserInfoBO();
    PagedList<UnitModel> paginate = ViewData["listConfig"] as PagedList<UnitModel>;
    var grid = new WebGrid(
                          rowsPerPage: paginate.PageSize,
                          canPage: true,
                          canSort: false,
                          ajaxUpdateContainerId: "gridConfig"
                          );

    grid.Bind(paginate,
    autoSortAndPage: false,
    rowCount: paginate.Count);
}
@{
    if (paginate.Count > 0)
    {
        var gridColumns = new List<WebGridColumn>();
        gridColumns.Add(grid.Column("STT", format: item => item.WebGrid.Rows.IndexOf(item) + 1
                + Math.Round(Convert.ToDouble(grid.TotalRowCount / grid.PageCount) / grid.RowsPerPage)
                * grid.RowsPerPage * grid.PageIndex));
        gridColumns.Add(grid.Column("UnitName", "Tên xã"));
        if (user.UnitLevel == GlobalConstant.UNIT_TYPE_PROVINCE) {
            gridColumns.Add(grid.Column("ParentName", "Tên huyện"));
        }
        gridColumns.Add(grid.Column(header: "Cấu hình", format: @<text>
            @if (item.DeviceConfigID != null && item.DeviceConfigID > 0)
            {
                <span class="label label-primary">Đã cấu hình</span>
            }
            else
            {
                <span class="label label-danger">Chưa cấu hình</span>
            }
        </text>));
        gridColumns.Add(grid.Column(header: "", format: @<text>
            <button class="btn btn-primary btn-sm" onclick="openConfig(@item.DeviceConfigID, @item.UnitID)"><i class="fa fa-edit"></i></button>
        </text>));

        @grid.GetHtml(htmlAttributes: new { id = "gridConfig" },
                                   fillEmptyRows: false,
                                   tableStyle: "table table-striped table-hover",
                                   alternatingRowStyle: "altRow",
                                   selectedRowStyle: "selectRow",
                                   columns: gridColumns)
        <div class="pagination">
            @Html.PagedListPager(paginate, page => Url.Action("SearchDevice",
                                   new
                                   {
                                       DistrictID = ViewBag.DistrictID,
                                       CommuneID = ViewBag.CommuneID,
                                       page,
                                       pageSize = paginate.PageSize

                                   }), PagedListRenderOptions.EnableUnobtrusiveAjaxReplacing(new AjaxOptions() { HttpMethod = "GET", UpdateTargetId = "divGridConfig" }))
        </div>
    }
    else
    {
        <div style="color:red; margin-left:10px;">
            Không có dữ liệu xã
        </div>
    }
}