eStream/Controllers/LiveController.cs
using eStream.Common.CommonClass;
using eStream.Common.CommonObject;
using eStream.Helpers.Filter;
using eStream.Models;
using Model;
using PagedList;
using System;
using System.Collections.Concurrent;
using System.Collections.Generic;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Web.Mvc;
using System.IO.Compression;
using NLog;
using System.Data.SqlClient;

namespace eStream.Controllers
{
    public class LiveController : BaseController
    {
        private static readonly Logger Logger = LogManager.GetCurrentClassLogger();
        private readonly Entities _context = new Entities();
        [BreadCrumb(ControllerName = "Phát trực tiếp", ActionName = "Cấu hình", AreaName = "")]
        public ActionResult Index()
        {
            UserInfoBO user = SessionManager.GetUserInfoBO();
            PrepareDataSearch(_context);
            var listLive = (from x in _context.Live
                            join u in _context.Unit on x.UnitID equals u.UnitID
                            where u.UnitID == user.UnitID
                            orderby x.LiveID descending
                            select new LiveModel
                            {
                                ChannelID = x.ChannelID,
                                LiveID = x.LiveID,
                                LiveType = x.LiveType,
                                Status = x.Status,
                                LiveSource = x.LiveSource,
                                UnitID = x.UnitID,
                                CreatedDate = x.CreatedDate
                            }).ToList();
            if (listLive.Any())
            {
                ViewData["nowLive"] = listLive[0];
            }
            else
            {
                var defaultChannelID = _context.ForwardChanel.Where(a => a.Status == GlobalConstant.IS_ACTIVE && a.IsDefault == GlobalConstant.IS_ACTIVE)
                    .Select(x => x.ChanelID)
                    .FirstOrDefault();

                var live = new Live
                {
                    LiveType = GlobalConstant.LIVE_TYPE_ALL,
                    CreatedDate = DateTime.Now,
                    Status = GlobalConstant.LIVE_DRAFF,
                    LiveSource = GlobalConstant.LIVE_SOURCE_VOV,
                    ChannelID = defaultChannelID,
                    UnitID = user.UnitID.Value
                };
                _context.Live.Add(live);
                _context.SaveChanges();
                ViewData["nowLive"] = new LiveModel
                {
                    ChannelID = live.ChannelID,
                    LiveID = live.LiveID,
                    LiveType = live.LiveType,
                    Status = live.Status,
                    LiveSource = live.LiveSource,
                    UnitID = live.UnitID,
                    CreatedDate = live.CreatedDate
                };
            }
            SystemConfig sc = _context.SystemConfig.FirstOrDefault();
            ViewData["systemConfig"] = sc;
            return View();
        }
        private void RemoveOneLive(Live live)
        {
            var listDevice = _context.LiveDevice.Where(x => x.LiveID == live.LiveID).ToList();
            _context.LiveDevice.RemoveRange(listDevice);
            var listFile = _context.LiveFile.Where(x => x.LiveID == live.LiveID).ToList();
            _context.LiveFile.RemoveRange(listFile);
            _context.Live.Remove(live);
        }
        public JsonResult RemoveDraffLive(long liveID)
        {
            UserInfoBO user = SessionManager.GetUserInfoBO();
            var live = _context.Live.Find(liveID);
            if (live.UnitID != user.UnitID)
            {
                throw new BusinessException("Dữ liệu không hợp lệ");
            }
            if (live.Status == GlobalConstant.LIVE_PLAYING)
            {
                throw new BusinessException("Chương trình đang phát không được xóa");
            }
            var listDevice = _context.LiveDevice.Where(x => _context.Live.Any(l => l.UnitID == user.UnitID && l.LiveID == x.LiveID && l.Status <= GlobalConstant.LIVE_WAIT && x.LiveID == liveID)).ToList();
            _context.LiveDevice.RemoveRange(listDevice);
            var listFile = _context.LiveFile.Where(x => _context.Live.Any(l => l.UnitID == user.UnitID && l.LiveID == x.LiveID && l.Status <= GlobalConstant.LIVE_WAIT && x.LiveID == liveID)).ToList();
            _context.LiveFile.RemoveRange(listFile);
            var lives = _context.Live.Where(x => x.Status <= GlobalConstant.LIVE_WAIT && x.LiveID == liveID).ToList();
            _context.Live.RemoveRange(lives);
            _context.SaveChanges();
            return Json("Xóa chương trình phát thành công", JsonRequestBehavior.AllowGet);
        }
        public JsonResult SaveDraffLive()
        {
            UserInfoBO user = SessionManager.GetUserInfoBO();
            var defaultChannelID = _context.ForwardChanel.Where(a => a.Status == GlobalConstant.IS_ACTIVE && a.IsDefault == GlobalConstant.IS_ACTIVE)
                    .Select(x => x.ChanelID)
                    .FirstOrDefault();
            Live live = new Live
            {
                CreatedDate = DateTime.Now,
                Status = GlobalConstant.LIVE_DRAFF,
                UnitID = user.UnitID.Value,
                LiveSource = GlobalConstant.LIVE_SOURCE_VOV,
                LiveType = GlobalConstant.LIVE_TYPE_ALL,
                ChannelID = defaultChannelID
            };
            _context.Live.Add(live);
            _context.SaveChanges();
            return Json(live.LiveID, JsonRequestBehavior.AllowGet);
        }

        public JsonResult RemoveDevice(long? liveID, int[] deviceIds)
        {
            UserInfoBO user = SessionManager.GetUserInfoBO();
            this.CheckDevicePermission(deviceIds);
            List<int> listDeviceID = deviceIds.Distinct().ToList();
            var listDevice = _context.LiveDevice.Where(x => listDeviceID.Contains(x.DeviceID) && x.LiveID == liveID).ToList();
            var live = _context.Live.Where(x => x.LiveID == liveID)
                .OrderByDescending(x => x.Status).FirstOrDefault();
            if (live != null)
            {

                foreach (var device in listDevice)
                {
                    _context.LiveDevice.Remove(device);
                }
                _context.SaveChanges();
            }
            return Json("", JsonRequestBehavior.AllowGet);
        }

        public JsonResult ChooseDevice(long? liveID, int[] deviceIds)
        {
            UserInfoBO user = SessionManager.GetUserInfoBO();
            this.CheckDevicePermission(deviceIds);
            List<int> listDeviceID = deviceIds.Distinct().ToList();
            List<Device> listDevice = _context.Device.Where(x => listDeviceID.Contains(x.DeviceID)).ToList();
            var live = _context.Live.Where(x => x.LiveID == liveID)
                .OrderByDescending(x => x.Status).FirstOrDefault();
            if (live != null)
            {
                foreach (Device device in listDevice)
                {
                    var liveDevice = new LiveDevice();
                    liveDevice.LiveID = liveID.Value;
                    liveDevice.DeviceID = device.DeviceID;
                    _context.LiveDevice.Add(liveDevice);
                }
                _context.SaveChanges();
            }
            return Json(liveID, JsonRequestBehavior.AllowGet);
        }

        public JsonResult CountDevice(long? liveID)
        {
            int countDevice = _context.LiveDevice.Where(x => x.LiveID == liveID).Count();
            return Json(countDevice, JsonRequestBehavior.AllowGet);
        }

        private void CheckDevicePermission(int[] deviceIds)
        {
            if (deviceIds == null || !deviceIds.Any())
            {
                throw new BusinessException("Bạn chưa lựa chọn thiết bị nào, vui lòng kiểm tra lại");
            }
            UserInfoBO user = SessionManager.GetUserInfoBO();
            string sUnit = "/" + user.UnitID + "/";
            List<int> listDeviceID = deviceIds.Distinct().ToList();
            int countDevice = _context.Device.Where(x => listDeviceID.Contains(x.DeviceID)
            && ((x.UnitID == null && user.UnitLevel == GlobalConstant.UNIT_TYPE_PROVINCE) || _context.Unit.Any(u => u.UnitID == x.UnitID && u.UnitPath.Contains(sUnit)))).Count();
            if (listDeviceID.Count != countDevice)
            {
                throw new BusinessException("Bạn không có quyền thực hiện các thao tác với các thiết bị vừa chọn, vui lòng kiểm tra lại");
            }
        }

        public PartialViewResult LoadListLive(long? liveID)
        {
            UserInfoBO user = SessionManager.GetUserInfoBO();
            var unit = _context.Unit.Find(user.UnitID);
            var listLive = (from x in _context.Live
                            join u in _context.Unit on x.UnitID equals u.UnitID
                            where x.Status >= GlobalConstant.LIVE_PLAYING
                            && unit.UnitPath.Contains(u.UnitPath)
                            orderby u.UnitPath descending, x.LiveID descending
                            select new LiveModel
                            {
                                ChannelID = x.ChannelID,
                                LiveID = x.LiveID,
                                LiveType = x.LiveType,
                                Status = x.Status,
                                LiveSource = x.LiveSource,
                                UnitID = x.UnitID,
                                CreatedDate = x.CreatedDate
                            }).ToList();
            if (liveID.GetValueOrDefault() == 0 && listLive.Any())
            {
                liveID = listLive[0].LiveID;
            }
            ViewData["listLive"] = listLive;
            ViewData["nowLiveID"] = liveID;
            return PartialView("_LstLive");

eStream/Views/Live/_AddText.cshtml
@using eStream.Models
@model ConvertTextModel
@{
    List<SelectListItem> Voices = ViewData["Voices"] as List<SelectListItem>;
}
@using (Ajax.BeginForm("AddToPlaylist", "Control", new AjaxOptions()
{
    HttpMethod = "post",
    OnBegin = "onBegin",
    OnSuccess = "onSuccessConvertText",
    OnFailure = "onFailConvertText"
}, new { id = "frmCreateOrEdit" }))
{
    @Html.AntiForgeryToken()
    <div class="modal-dialog" style="width: 750px !important">
        <!-- Modal content-->
        <div class="modal-content">
            <div class="ibox-title">
                <h5>Cấu hình chuyển đổi văn bản sang audio</h5>
                <div class="ibox-tools">
                    <a class="close-link" data-dismiss="modal">
                        <i class="fa fa-times"></i>
                    </a>
                </div>
            </div>

            <div class="modal-body">
                <div class="row">
                    <div class="form-horizontal">
                        <div class="col-md-12 m-b-sm m-t-sm" id="divConvertText" style="display: none">
                            <div class="progress progress-striped active">
                                <div style="width: 100%" class="progress-bar progress-bar-success">
                                </div>
                            </div>
                        </div>
                        <div class="col-md-12">
                            <div class="form-group">
                                <label class="col-sm-2 control-label" for="">Tiêu đề<span class="text-danger"> *</span></label>
                                <div class="col-sm-10">
                                    @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control", style = "width: 100%" } })
                                    @Html.ValidationMessageFor(model => model.Title)
                                </div>
                            </div>
                        </div>
                        <div class="col-md-12">
                            <div class="form-group">
                                <label class="col-sm-2 control-label" for="">Nội dung<span class="text-danger"> *</span></label>
                                <div class="col-sm-10">
                                    @Html.TextAreaFor(model => model.Text, new { @class = "form-control", @rows = "13" })
                                    @Html.ValidationMessageFor(model => model.Text)
                                </div>
                            </div>
                        </div>
                        <div class="col-md-12">
                            <div class="form-group">
                                <label class="col-sm-2 control-label" for="">Giọng đọc</label>
                                <div class="col-sm-10">
                                    @Html.DropDownListFor(x => x.Voice, Voices, new { @class = "form-control chosen-select", style = "width: 100%" })
                                </div>
                            </div>
                        </div>
                        <div class="col-md-12">
                            <div class="form-group">
                                <label class="col-sm-2 control-label" for="">Tốc độ đọc</label>
                                <div class="col-sm-6">
                                    <input type="range" class="slider" style="margin-top: 10px !important; background-image:-webkit-gradient(linear, left top, right top, color-stop(0.526, #1c84c6), color-stop(0.526, #C5C5C5))" value="1" onchange="setVolumeConvert(this)" oninput="showValConvert(this)" data-orientation="vertical" min="0.1" max="1.9" step="0.1" />
                                </div>
                                <div class="col-sm-2">
                                    @Html.TextBoxFor(x => x.Rate, new { @class = "form-control", @id = "rate_id", @readonly = "true" })
                                    @Html.ValidationMessageFor(model => model.Rate)
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button type="submit" class="btn btn-primary" id="btnConvertText"><i class="fa fa-cloud-upload"></i> Chuyển giọng nói</button>
                <button type="button" class="btn btn-default pull-left" data-dismiss="modal" onclick="loadLive(@Model.LiveID, 1)">Đóng</button>
            </div>
        </div>
    </div>
    @Html.HiddenFor(a => a.LiveID)
}
<script type="text/javascript">
    var intervalCheckConvert = null;
    $(document).ready(function () {
        $("#rate_id").val(1);
        $("select").chosen({ width: "100%" });
        $('.i-checks').iCheck({
            checkboxClass: 'icheckbox_square-green',
            radioClass: 'iradio_square-green',
        });
        $.validator.unobtrusive.parse("#frmCreateOrEdit");
    });
    function onBegin() {
        if ($("#frmCreateOrEdit").valid()) {
            $("#btnConvertText").attr("disabled", true);
            $('#divConvertText').show();
            return true;
        } else {
            return false;
        }
    }
    function showValConvert(item) {
        var val = (item.value - $(item).attr('min')) / ($(item).attr('max') - $(item).attr('min'));
        $(item).css('background-image',
            '-webkit-gradient(linear, left top, right top, '
            + 'color-stop(' + val + ', #1c84c6), '
            + 'color-stop(' + val + ', #C5C5C5)'
            + ')'
        );
    }

    function setVolumeConvert(item) {
        $("#rate_id").val(item.value);
    }
</script>

eStream/Views/Live/_File.cshtml
@using eStream.Models
@using Model
@using eStream.Common.CommonClass
@model LiveModel
@{
    List<LiveFile> listFile = ViewData["listFile"] as List<LiveFile>;
    int isEdit = (int)ViewData["isEdit"];
    var len = listFile.Count;
    var idx = 1;
    var isLoop = Model.IsLoop ? GlobalConstant.IS_ACTIVE : 0;
}
@if (listFile != null && listFile.Any())
{
    <div class="row">
        <div class="col-md-12">
            <table class="table table-hover">
                <tbody>
                    @foreach (var file in listFile)
                    {
                        <tr>
                            <td style="width:60%">
                                <i class="fa fa-microphone"></i>  <a href="@Url.Action("Download", "Live", new { LiveFileID = file.LiveFileID })">@file.Title</a>
                            </td>
                            <td>
                                @file.CreatedUser
                            </td>
                            <td>
                                @string.Format("{0:dd/MM/yyyy HH:mm:ss}", file.CreatedDate)
                            </td>

                            @if (isEdit == GlobalConstant.IS_ACTIVE && Model != null && Model.Status.GetValueOrDefault() != GlobalConstant.LIVE_PLAYING)
                            {
                                <td>
                                    <span class="pull-right">
                                        @if (idx > 1)
                                        {
                                            <button class="btn btn-xs btn-primary" title="Chuyển lên" onclick="move(@file.LiveID, @file.LiveFileID, 1)"><i class="fa fa-angle-double-up"></i></button>
                                        }
                                        @if (idx < len)
                                        {
                                            <button class="btn btn-xs btn-primary" title="Chuyển xuống" onclick="move(@file.LiveID, @file.LiveFileID, -1)"><i class="fa fa-angle-double-down"></i></button>
                                        }
                                        <button class="btn btn-xs btn-danger" onclick="deleteFile(@file.LiveFileID)"><i class="fa fa-trash-o"></i></button>
                                    </span>
                                </td>
                                idx++;
                            }
                        </tr>
                    }
                </tbody>
            </table>
            <input type="hidden" id="hasFile" value="1" />
        </div>
    </div>
    <div class="row">
        <div class="col-md-2">
            <div class="form-group">
                <div class="i-checks">
                    <label>@Html.CheckBoxFor(x => x.IsLoop) Phát lặp</label>
                </div>
                <input type="hidden" value="@Model.IsLoop.ToString()" id="hidIsLoop" />
            </div>
        </div>
        <div class="col-md-4" id="InpLoopCount">
            <div class="form-horizontal">
                <div class="form-group">
                    <label class="col-md-4 control-label">Số lần lặp</label>
                    <div class="col-md-6">
                        <div class="input-group">
                            @Html.TextBoxFor(x => x.LoopCount, new { @class = "form-control", style = "width: 100%", @id = "LoopCount" })
                            <span class="input-group-addon">
                                Lần
                            </span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
}

<script type="text/javascript">
    $(document).ready(function () {
        var hasFile = $("#hasFile").val();
        if (hasFile) {
            $('#btnReplayFromStart').show();
        } else {
            $('#btnReplayFromStart').hide();
        }
        $("select").chosen({ width: "100%" });
        changeLoop(@isLoop)
        $('input[name="IsLoop"]').on('ifClicked', function (event) {
            changeLoop(!event.target.checked);
        });
    });

    function changeLoop(checked) {
        if (checked || checked == 1 || checked == true) {
            if ($("#LoopCount").val() == '') {
                $("#LoopCount").val('@GlobalConstant.LOOP_COUNT');
            }
            $("#InpLoopCount").show();
            $("#hidIsLoop").val(true);
        } else {
            $("#LoopCount").val('');
            $("#InpLoopCount").hide();
            $("#hidIsLoop").val(false);
        }
    }
</script>

eStream/Views/Live/_LstDevice.cshtml
@using eStream.Common.CommonClass;
@using eStream.Common.CommonObject;
@using eStream.Models;
@using PagedList;
@using PagedList.Mvc;
@{
    /**/

    /**/

    UserInfoBO user = SessionManager.GetUserInfoBO();
    PagedList<DeviceModel> paginate = ViewData["listDevice"] as PagedList<DeviceModel>;
    var grid = new WebGrid(
                          rowsPerPage: paginate.PageSize,
                          canPage: true,
                          canSort: false,
                          ajaxUpdateContainerId: "gridDevice"
                          );

    grid.Bind(paginate,
    autoSortAndPage: false,
    rowCount: paginate.Count);
}
@{
    if (paginate.Count > 0)
    {
        var gridColumns = new List<WebGridColumn>();
        gridColumns.Add(grid.Column(header: "Tên thiết bị", format: @<text>
    <input type="hidden" value="@item.DeviceID" name="deviceIds" />
    @item.DeviceNameWithVolume
    @if (item.StatusBO.IsVolumeOn(1))
    {
        <i id="volstatus_1_@item.DeviceID" class="fa fa-volume-down" style="color:#1ab394;font-size:14px">
            &nbsp;
        </i>
    }
    else
    {
        <i id="volstatus_1_@item.DeviceID" class="fa fa-volume-down">
            &nbsp;
        </i>
    }
    @if (item.StatusBO.IsVolumeOn(2))
    {
        <i id="volstatus_2_@item.DeviceID" class="fa fa-volume-down" style="color:#1ab394;font-size:14px">
            &nbsp;
        </i>
    }
    else
    {
        <i id="volstatus_2_@item.DeviceID" class="fa fa-volume-down">
            &nbsp;
        </i>
    }
    @if (item.StatusBO.IsVolumeOn(3))
    {
        <i id="volstatus_3_@item.DeviceID" class="fa fa-volume-down" style="color:#1ab394;font-size:14px">
            &nbsp;
        </i>
    }
    else
    {
        <i id="volstatus_3_@item.DeviceID" class="fa fa-volume-down">
            &nbsp;
        </i>
    }
    @if (item.StatusBO.IsVolumeOn(4))
    {
        <i id="volstatus_4_@item.DeviceID" class="fa fa-volume-down" style="color:#1ab394;font-size:14px"> )</i>
    }
    else
    {
        <i id="volstatus_4_@item.DeviceID" class="fa fa-volume-down"> )</i>
    }
        </text>));
 gridColumns.Add(grid.Column(header: "Trạng thái", style: "with-10", format: @<text>
    @if (item.StatusBO.IsPlaying == GlobalConstant.IS_ACTIVE)
    {
        <span class="label badge label-primary" id="status_@item.DeviceID" style="width:40px">Bật</span>
    }
    else if (item.StatusBO.IsStop == GlobalConstant.IS_ACTIVE)
    {
        <span class="label badge label-danger" id="status_@item.DeviceID" style="width:40px">Tắt</span>
    }
    else
    {
        <span class="label badge label-default" id="status_@item.DeviceID" style="width:40px">N/A</span>
    }
</text>));
gridColumns.Add(grid.Column(header: "Kết nối", style: "with-10", format: @<text>

    @if (item.StatusBO.IsOnline == GlobalConstant.IS_ACTIVE)
    {
        <span class="label badge label-primary" id="online_@item.DeviceID" style="width:40px">Có</span>
    }
    else
    {
        <span class="label badge label-default" id="online_@item.DeviceID" style="width:40px">Không</span>
    }
</text>));
gridColumns.Add(grid.Column(header: "Mạng", format: @<text>
    <div id="netdisClass_@item.DeviceID" class="@item.DeviceExt.Display.ClassDis"></div><div id="netdisText_@item.DeviceID">@item.DeviceExt.Display.SortDis</div>
</text>));
gridColumns.Add(grid.Column(header: "Thao tác", style: "with-20", format: @<text>
    <a href="javascript:void(0)" id="btnChangeVolumeSlider_@item.DeviceID" rel="popover">
        <i class="fa fa-volume-up" style="font-size:14px"></i> @item.Volume
    </a>
    <script>
        $(document).ready(function () {
            $("#btnChangeVolumeSlider_@item.DeviceID").popover({
                html: true,
                animation: false,
                content: '<input type="range" class="slider" style="background-image:-webkit-gradient(linear, left top, right top, color-stop(@item.VolumePercent, #1c84c6), color-stop(@item.VolumePercent, #C5C5C5))" id="range_@item.DeviceID" value="@item.Volume" onchange="setVolume(this, @item.DeviceID)" oninput="showVal(this, @item.DeviceID)" slider_device="@item.DeviceID" data-orientation="vertical" min="0" max="100" step="1" />',
                placement: "top"
            });
        });
    </script>
    <a href="javascript:void(0)" onclick="viewInfo(@item.DeviceID)" data-toggle="modal" data-target="#modal-log" title="Thông tin thiết bị"><i class="fa fa-info-circle" style="font-size:18px"></i></a>
    <a href="javascript:void(0)" onclick="viewChart(@item.DeviceID, '', 0)" data-toggle="modal" data-target="#modal-log" title="Biểu đồ hoạt động"><i class="fa fa-bar-chart" style="font-size:18px"></i></a>
    <a href="javascript:void(0)" onclick="viewLog(@item.DeviceID)" data-toggle="modal" data-target="#modal-log" title="Xem log thiết bị"><i class="fa fa-history" style="font-size:18px"></i></a>
    @if (item.DeviceExt.Loc != null && item.DeviceExt.Loc.Lat != "" && item.DeviceExt.Loc.Long != "")
    {
        <a id="viewLoc_@item.DeviceID" onclick="viewLoc(this, '@item.DeviceName','@item.DeviceExt.Loc.Lat', '@item.DeviceExt.Loc.Long')" title="Xem vị trí thiết bị"><i class="fa fa-map-marker" style="font-size:18px"></i></a>
    }
    else
    {
        <a id="viewLoc_@item.DeviceID" onclick="viewLoc(this, '@item.DeviceName','@item.DeviceExt.Loc.Lat', '@item.DeviceExt.Loc.Long')" class="disabled-icon" title="Xem vị trí thiết bị"><i class="fa fa-map-marker" style="font-size:18px"></i></a>
    }
    @if (item.DeviceExt.ProName != "")
    {
        <a id="viewSms_@item.DeviceID" onclick="viewSms(this, @item.DeviceID)" title="Quản lý SMS của thiết bị"><i class="fa fa-telegram" style="font-size:18px"></i></a>
    }
    else
    {
        <a id="viewSms_@item.DeviceID" onclick="viewSms(this, @item.DeviceID)" class="disabled-icon" title="Quản lý SMS của thiết bị"><i class="fa fa-telegram" style="font-size:18px"></i></a>
    }
</text>));

@grid.GetHtml(htmlAttributes: new { id = "gridDevice" },
                        fillEmptyRows: false,
                        tableStyle: "table table-striped table-hover",
                        alternatingRowStyle: "altRow",
                        selectedRowStyle: "selectRow",
                        columns: gridColumns)
<div class="pagination">
    @Html.PagedListPager(paginate, page => Url.Action("SearchDevice",
                            new
                            {
                                SearchDeviceName = ViewBag.DeviceName,
                                UnitID = ViewBag.UnitID,
                                Status = ViewBag.Status,
                                Connect = ViewBag.Connect,
                                page,
                                pageSize = paginate.PageSize

                            }), PagedListRenderOptions.EnableUnobtrusiveAjaxReplacing(new AjaxOptions() { HttpMethod = "GET", UpdateTargetId = "divListDevice" }))
</div>
}
else
{
<div style="color:red; margin-left:10px;">
    Không có thiết bị nào
</div>
}
}
<script type="text/javascript">
    function showVal(item, deviceID) {
        var val = (item.value - $(item).attr('min')) / ($(item).attr('max') - $(item).attr('min'));
        $(item).css('background-image',
            '-webkit-gradient(linear, left top, right top, '
            + 'color-stop(' + val + ', #1c84c6), '
            + 'color-stop(' + val + ', #C5C5C5)'
            + ')'
        );
        $('#btnChangeVolumeSlider_' + deviceID).html('<i class="fa fa-volume-up" style="font-size:14px;"></i> ' + item.value);
    }

    function setVolume(item, deviceID) {
        $.ajax({
            type: "POST",
            url: '@Url.Action("SaveVolume", "Manager")',
            data: { "DeviceID": deviceID, "Volume": item.value },
            success: function (msg) {
                CommonJS.alert(msg);
            },
            error: function (e) {
                CommonJS.alert(e.responseText);
            }
        });
    }
</script>

eStream/Views/Live/_LstLive.cshtml
@using eStream.Common.CommonClass;
@using eStream.Models;
@{
    List<LiveModel> listLive = ViewData["listLive"] as List<LiveModel>;
    if (listLive == null)
    {
        listLive = new List<LiveModel>();
    }
    long? liveID = ViewData["nowLiveID"] as long?;
}
@if (listLive.Any())
{
    <div class="ibox">
        <div class="ibox-content no-padding">
            <div class="list-group">
                @foreach (var item in listLive)
                {
                    string activeClass = string.Empty;
                    if (item.LiveID == liveID.GetValueOrDefault())
                    {
                        activeClass = "active";
                    }
                    string badgeClass = string.Empty;
                    string statusName = "Đang cấu hình";
                    if (item.Status == GlobalConstant.LIVE_WAIT)
                    {
                        badgeClass = "badge-success";
                        statusName = "Chưa phát";
                    }
                    else if (item.Status == GlobalConstant.LIVE_PLAYING)
                    {
                        badgeClass = "badge-primary";
                        statusName = "Đang phát";
                    }
                    else if (item.Status == GlobalConstant.LIVE_STOPED)
                    {
                        badgeClass = "badge-warning";
                        statusName = "Đã kết thúc";
                    }
                    <a href="javascript:void(0)" id="aLiveLi_@item.LiveID" onclick="loadLive(@item.LiveID); loadLiveName('@item.LiveID')" class="list-group-item @activeClass">
                        @item.CreatedDate.Value.ToString("dd/MM/yyyy") <span class="badge @badgeClass">@statusName</span>
                        <br />
                        <small>@item.LiveID</small>
                    </a>
                }
            </div>
        </div>
    </div>
}