eStream/Controllers/FmController.cs
using eStream.Common.CommonClass;
using eStream.Common.CommonObject;
using eStream.Helpers.Filter;
using eStream.Models;
using Model;
using PagedList;
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace eStream.Controllers
{
    public class FmController : BaseController
    {
        private readonly Entities _context = new Entities();
        [BreadCrumb(ControllerName = "Giám sát FM", ActionName = "Danh sách", AreaName = "")]
        public ActionResult Index()
        {
            PrepareDataSearch(_context);
            SystemConfig sc = _context.SystemConfig.FirstOrDefault();
            int timeRefresh = (sc != null && sc.RefreshTime.GetValueOrDefault() > 0) ? sc.RefreshTime.GetValueOrDefault() : GlobalConstant.DEFAULT_TIME_REFRESH;
            ViewData["timeRefresh"] = timeRefresh;
            return View("index");
        }

        public PartialViewResult SearchDevice(int? UnitID, string SearchDeviceName = null, int Status = 0, int Connect = 0, int page = 1)
        {
            UserInfoBO user = SessionManager.GetUserInfoBO();
            if (string.IsNullOrWhiteSpace(SearchDeviceName))
            {
                SearchDeviceName = null;
            }
            else
            {
                SearchDeviceName = SearchDeviceName.Trim().ToLower();
            }
            var query = from d in _context.Device
                        where d.Status == GlobalConstant.IS_ACTIVE
                        && d.FmType == GlobalConstant.IS_ACTIVE
                        && (SearchDeviceName == null || d.DeviceCode.ToLower().Contains(SearchDeviceName) || d.DeviceName.ToLower().Contains(SearchDeviceName))
                        select d;
            string sUnitID = "/" + user.UnitID + "/";
            string sUnitSearchID = "/" + UnitID.GetValueOrDefault() + "/";
            if (UnitID == null || UnitID == 0)
            {
                query = query.Where(o => (o.UnitID == null && user.UnitLevel == GlobalConstant.UNIT_TYPE_PROVINCE)
                        || _context.Unit.Any(u => u.Status == GlobalConstant.IS_ACTIVE
                        && u.UnitID == o.UnitID && (user.IsSupperAdmin == GlobalConstant.IS_ACTIVE || u.UnitPath.Contains(sUnitID))));
            }
            else
            {
                query = query.Where(o => _context.Unit.Any(u => u.Status == GlobalConstant.IS_ACTIVE
                        && u.UnitID == o.UnitID && (user.IsSupperAdmin == GlobalConstant.IS_ACTIVE || u.UnitPath.Contains(sUnitID))
                        && u.UnitPath.Contains(sUnitSearchID)));
            }
            SystemConfig sc = _context.SystemConfig.FirstOrDefault();
            int timeout = sc != null ? sc.PlayingTimeout.GetValueOrDefault() : 0;
            var queryModel = query.Select(x => new DeviceModel
            {
                UnitID = x.UnitID,
                UnitName = _context.Unit.Where(u => u.UnitID == x.UnitID && u.UnitLevel == GlobalConstant.UNIT_TYPE_COMMUNE).Select(u => u.UnitName).FirstOrDefault(),
                DeviceID = x.DeviceID,
                SDeviceCode = x.DeviceCode,
                ManagerName = x.ManagerName,
                Status = x.Status,
                CreateDate = x.CreateDate,
                DeviceName = x.DeviceName,
                Version = x.Version,
                Volume = x.Volume,
                Timeout = timeout
            }).OrderBy(x => x.UnitID).ThenBy(x => x.DeviceName).ThenBy(x => x.SDeviceCode);
            if (Status == 0 && Connect == 0)
            {
                PagedList<DeviceModel> paginate = new PagedList<DeviceModel>(queryModel, page, GlobalConstant.PAGE_SIZE);
                ViewData["listDevice"] = paginate;
            }
            else
            {
                var listDevice = queryModel.ToList();

                int[] deviceIds = listDevice.Select(x => x.DeviceID).ToArray();
                List<StatusBO> listDeviceStatus = ManagerController.GetDeviceStatus(_context, deviceIds);
                Dictionary<int, int> dicStatus = new Dictionary<int, int>();
                foreach (StatusBO nowStatus in listDeviceStatus)
                {
                    if (Status > 0 && !ManagerController.IsValidStatus(Status, nowStatus))
                    {
                        continue;
                    }
                    if (Connect > 0 && !ManagerController.IsValidConnect(Connect, nowStatus))
                    {
                        continue;
                    }
                    dicStatus[nowStatus.ID] = GlobalConstant.IS_ACTIVE;
                }
                List<DeviceModel> listFinalDevice = new List<DeviceModel>();
                foreach (var device in listDevice)
                {
                    if (dicStatus.ContainsKey(device.DeviceID))
                    {
                        listFinalDevice.Add(device);
                    }
                }
                PagedList<DeviceModel> paginate = new PagedList<DeviceModel>(listFinalDevice, page, GlobalConstant.PAGE_SIZE);
                ViewData["listDevice"] = paginate;
            }
            ViewBag.DeviceName = SearchDeviceName;
            ViewBag.UnitID = UnitID;
            ViewBag.Status = Status;
            ViewBag.Connect = Connect;
            return PartialView("_LstDevice");
        }

        public PartialViewResult OpenConfig(int deviceID)
        {
            UserInfoBO user = SessionManager.GetUserInfoBO();
            string sUnit = "/" + user.UnitID + "/";
            Device device = _context.Device.Where(d => d.DeviceID == deviceID && d.Status == GlobalConstant.IS_ACTIVE
            && _context.Unit.Any(x => x.Status == GlobalConstant.IS_ACTIVE
            && x.UnitID == d.UnitID && (user.IsSupperAdmin == GlobalConstant.IS_ACTIVE || x.UnitPath.Contains(sUnit)))).FirstOrDefault();
            if (device != null)
            {
                DeviceModel model = new DeviceModel();
                model.DeviceID = device.DeviceID;
                model.UnitID = device.UnitID;
                model.Volume = device.Volume;
                model.SyncTime = device.SyncTime;
                model.Bitrate = device.Bitrate;
                model.IsSMS = device.IsSMS.GetValueOrDefault() == GlobalConstant.IS_ACTIVE ? true : false;
                model.DeviceName = device.DeviceName;
                model.NoVov = device.NoVov;
                model.Timer = device.Timer;
                // cac list du lieu
                List<SelectListItem> listBitrate = new List<SelectListItem>();
                listBitrate.Add(new SelectListItem { Value = "", Text = "--Mặc định--" });
                listBitrate.Add(new SelectListItem { Value = "32", Text = "32kbps" });
                listBitrate.Add(new SelectListItem { Value = "64", Text = "64kbps" });
                listBitrate.Add(new SelectListItem { Value = "128", Text = "128kbps" });
                ViewData["listBitrate"] = listBitrate;
                return PartialView("_Config", model);
            }
            else
            {
                throw new BusinessException("Không tồn tại thiết bị hoặc thiết bị không thuộc quản lý của đơn vị bạn");
            }
        }

        public JsonResult SaveConfig(DeviceModel model)
        {
            UserInfoBO user = SessionManager.GetUserInfoBO();
            string sUnit = "/" + user.UnitID + "/";
            Device device = _context.Device.Where(d => d.DeviceID == model.DeviceID && d.Status == GlobalConstant.IS_ACTIVE
            && _context.Unit.Any(x => x.Status == GlobalConstant.IS_ACTIVE
            && x.UnitID == d.UnitID && (user.IsSupperAdmin == GlobalConstant.IS_ACTIVE || x.UnitPath.Contains(sUnit)))).FirstOrDefault();
            if (device != null)
            {
                device.IsChangeSyncTime = GlobalConstant.IS_ACTIVE;
                device.IsChangeVolume = GlobalConstant.IS_ACTIVE;
                DeviceCommandCaching.AddCommand(device.DeviceID, GlobalConstant.DEVICE_COMMAND_CHANGE_VOLUME);
                DeviceCommandCaching.AddCommand(device.DeviceID, GlobalConstant.DEVICE_COMMAND_CHECK_INTERVAL);
                //device.IsChangeTimer = GlobalConstant.IS_ACTIVE;
                device.Volume = model.Volume;
                device.SyncTime = model.SyncTime;
                device.Bitrate = model.Bitrate;
                device.IsSMS = null;
                device.NoVov = model.NoVov;
                device.Timer = model.Timer;
                if (model.IsSMS)
                {
                    device.IsSMS = GlobalConstant.IS_ACTIVE;
                }
                _context.SaveChanges();
                return Json("Cấu hình thành công", JsonRequestBehavior.AllowGet);
            }
            else
            {
                throw new BusinessException("Không tồn tại thiết bị hoặc thiết bị không thuộc quản lý của đơn vị bạn");
            }
        }

        public PartialViewResult ViewLog(int DeviceID, int page = 1)
        {
            Device device = _context.Device.Find(DeviceID);
            if (device == null)
            {
                throw new BusinessException("Không tồn tại thiết bị");
            }
            ViewData["deviceName"] = device.DeviceName;
            ViewData["deviceID"] = device.DeviceID;
            return PartialView("_ViewLog");
        }

        public PartialViewResult SearchLog(int DeviceID, short? LogType, string FromDate, string ToDate, int page = 1)
        {
            Device device = _context.Device.Find(DeviceID);
            if (device == null)
            {
                throw new BusinessException("Không tồn tại thiết bị");
            }
            var iQuery = _context.DeviceLog.Where(x => x.DeviceID == DeviceID && (LogType == null || x.LogCode == LogType))
                .Select(x => new DeviceLogModel
                {
                    DeviceLogID = x.DeviceLogID,

eStream/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
@using eStream.Helpers
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>EStreaming | @ViewBag.Title</title>
    <link href='https://fonts.googleapis.com/css?family=Open+Sans:400,300,600,700' rel='stylesheet' type='text/css'>
    <script type="text/javascript" src="~/Scripts/hls.min.js"></script>
    @Styles.Render("~/font-awesome/css")
    @Styles.Render("~/Content/inews/css")
    @Styles.Render("~/plugins/awesomeCheckboxStyles")
    @Styles.Render("~/plugins/clockpickerStyles")
    @Styles.Render("~/plugins/dateRangeStyles")
    @Styles.Render("~/Content/plugins/iCheck/iCheckStyles")
    @Styles.Render("~/Content/plugins/chosen/chosenStyles")
    @Styles.Render("~/plugins/jasnyBootstrapStyles")
    @Styles.Render("~/plugins/dataPickerStyles")
    @Styles.Render("~/plugins/imagecropperStyles")
    @Styles.Render("~/Content/plugins/colorpicker/colorpickerStyles")
    @Styles.Render("~/plugins/select2Styles")
    @Styles.Render("~/plugins/touchSpinStyles")
    @Styles.Render("~/plugins/tagInputsStyles")
    @Styles.Render("~/plugins/duallistStyles")
    @Styles.Render("~/plugins/toastrStyles")
    @Styles.Render("~/plugins/summernoteStyles")
    @Styles.Render("~/Content/plugins/dropzone/dropZoneStyles")
    @Styles.Render("~/Content/css")
    @Styles.Render("~/Content/treeview")
    <style type="text/css">

        .with-20 {
            width: 20% !important;
        }

        .with-10 {
            width: 10% !important;
        }

        .with-12 {
            width: 12% !important;
        }

        .slider {
            -webkit-appearance: none;
            width: 100%;
            height: 10px;
            border-radius: 5px;
            background: #C5C5C5;
            outline: none;
            -webkit-transition: .2s;
            transition: opacity .2s;
        }

            .slider::-webkit-slider-thumb {
                -webkit-appearance: none;
                appearance: none;
                width: 20px;
                height: 20px;
                border-radius: 50%;
                background: #1c84c6;
                cursor: pointer;
            }

            .slider::-moz-range-thumb {
                width: 25px;
                height: 25px;
                border-radius: 50%;
                background: #1c84c6;
                cursor: pointer;
            }

        .table-pager {
            text-align: left;
        }

            .table-pager > td {
                padding-top: 10px;
            }

                .table-pager > td > a {
                    background-color: #f5f5f5;
                    border: 1px solid #ccc;
                    border-radius: 3px;
                    padding: 3px 7px;
                }

                    .table-pager > td > a:hover {
                        background-color: #f0f0f0;
                    }

        .signal0 {
            margin-top: 2px;
            background: url('/Content/images/signal.png') no-repeat 0px 0px;
            width: 20px;
            height: 13px;
            float: left;
        }

        .signal1 {
            margin-top: 2px;
            background: url('/Content/images/signal.png') no-repeat 0px -12px;
            width: 20px;
            height: 13px;
            float: left;
        }

        .signal2 {
            margin-top: 2px;
            background: url('/Content/images/signal.png') no-repeat 0px -24px;
            width: 20px;
            height: 13px;
            float: left;
        }

        .signal3 {
            margin-top: 2px;
            background: url('/Content/images/signal.png') no-repeat 0px -36px;
            width: 20px;
            height: 13px;
            float: left;
        }

        .signal4 {
            margin-top: 2px;
            background: url('/Content/images/signal.png') no-repeat 0px -48px;
            width: 20px;
            height: 13px;
            float: left;
        }

        .wifi {
            margin-top: 2px;
            background: url('/Content/images/signal.png') no-repeat 0px -60px;
            width: 20px;
            height: 13px;
            float: left;
        }

        .lan {
            margin-top: 2px;
            background: url('/Content/images/signal.png') no-repeat 0px -73px;
            width: 20px;
            height: 13px;
            float: left;
        }
    </style>
</head>
<body>
    <div id="wrapper" class="@Html.PageClass()">
        <!-- Navigation -->
        @Html.Partial("_Navigation")
        <!-- Page wraper -->
        <div id="page-wrapper" class="gray-bg @ViewBag.SpecialClass">
            <!-- Top Navbar -->
            @Html.Partial("_TopNavbar")
            <!-- Main view  -->
            <div class="row wrapper border-bottom white-bg page-heading">
                <div class="col-lg-10">
                    <h2>@ViewBag.FunctionName</h2>
                    @Html.Raw(Html.BuildBreadcrumbNavigation())
                </div>
                <div class="col-lg-2">
                </div>
            </div>
            <div class="wrapper wrapper-content animated fadeIn">
                <div id="_GlobalMessage">
                </div>
                <!-- Section for main scripts render -->
                @Scripts.Render("~/bundles/jquery")
                @Scripts.Render("~/bundles/bootstrap")
                @Scripts.Render("~/plugins/slimScroll")
                @Scripts.Render("~/plugins/nouiSlider")
                @Scripts.Render("~/bundles/inspinia")
                @Scripts.Render("~/bundles/modernizr")
                @Scripts.Render("~/bundles/eStream")
                @Scripts.Render("~/plugins/chosen")
                @Scripts.Render("~/plugins/iCheck")
                @Scripts.Render("~/plugins/dataPicker")
                @Scripts.Render("~/plugins/ionRange")
                @Scripts.Render("~/plugins/jasnyBootstrap")
                @Scripts.Render("~/plugins/knob")
                @Scripts.Render("~/plugins/imagecropper")
                @Scripts.Render("~/plugins/colorpicker")
                @Scripts.Render("~/plugins/clockpicker")
                @Scripts.Render("~/plugins/dateRange")
                @Scripts.Render("~/plugins/select2")
                @Scripts.Render("~/plugins/touchSpin")
                @Scripts.Render("~/plugins/tagInputs")
                @Scripts.Render("~/plugins/duallist")
                @Scripts.Render("~/plugins/peity")
                @Scripts.Render("~/plugins/toastr")
                @Scripts.Render("~/plugins/summernote")
                @Scripts.Render("~/plugins/typehead")
                @Scripts.Render("~/plugins/dropZone")
                <!-- Skin config script - only for demo purpose-->
                @Scripts.Render("~/bundles/skinConfig")
                @Scripts.Render("~/bundles/treeview")
                @Scripts.Render("~/plugins/chartJs")
                <!-- Handler for local scripts -->
                @RenderSection("scripts", required: false)
                @RenderBody()
                <div id="modal-change-password" class="modal fade" role="dialog"></div>
                <div id="modal-playing-live" class="modal fade" role="dialog"></div>
            </div>
            <div class="footer">
                <div class="pull-right">
                    Hỗ trợ kỹ thuật: <strong><a href="tel:0963250260">0963 250 260</a></strong>
                </div>
                <div>
                    <strong>Copyright © 2018 by <a href="mailto:inetvn@gmail.com">Duc Khanh Technology Co.,Ltd</a>.</strong>
                </div>
            </div>
        </div>
    </div>
</body>
</html>
<script type="text/javascript">
    $(document).ready(function () {
        displayLivingMenu();
    });

    $.ajaxSetup({
        error: function (x, e) {
            if (x.status == 401) {
                window.location.reload();
            }
        }
    });

    function displayLivingMenu() {
        $.ajax({
            type: "POST",
            url: '@Url.Action("GetNowPlaying", "Live")',
            success: function (data) {
                if (data == 0) {
                    $('#aMenuLive').removeClass('field-validation-error');
                    $('#aMenuLive').css('width', 'auto');
                    $('#aMenuLive').css('display', 'block');
                    var nextItem = $('#aMenuLive').next();
                    if (nextItem.attr('id') == 'aImageLiving') {
                        nextItem.remove();
                    }
                } else if (!$('#aMenuLive').hasClass('field-validation-error')) {
                    $('#aMenuLive').addClass('field-validation-error');
                    $('#aMenuLive').css('width', '85%');
                    $('#aMenuLive').css('display', 'inline-block');
                    $('#aMenuLive').after('<a id="aImageLiving" style="width:15%;display:inline-block;padding-left:0px;"><img src="/Content/images/live.gif" href="javascript:void(0)" data-toggle="modal" data-target="#modal-playing-live" onclick="openLivePop()" style="width:25px;"></a>');
                }
            },
            error: function (e) {
            }
        });
    }

    function openLivePop() {
        $.ajax({
            type: "GET",
            url: '@Url.Action("GetPlayingLives", "Live")',
            data: {},
            success: function (data) {
                $('#modal-playing-live').html(data);
            },
            error: function (xhr) {
                CommonJS.alert(xhr.responseText);
            }
        });
    }

    function ChangePassPopup() {
        $.ajax({
            type: "GET",
            url: '@Url.Action("ChangePassword", "Home")',
            data: {},
            success: function (data) {
                $('#modal-change-password').html(data);
            },
            error: function (xhr) {
                CommonJS.alert(xhr.responseText);
            }
        });
    }
</script>

eStream/Views/Shared/_Login.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>ESt | Login</title>
    @Styles.Render("~/Content/css")
    @Styles.Render("~/Content/plugins/iCheck/iCheckStyles")
</head>
<body class="gray-bg">
    <div class="middle-box text-center loginscreen  animated fadeInDown">
        <div>
            <div>
                <h1 class="logo-name">ESt</h1>
            </div>
            <h3>Hệ thống quản lý phát thanh</h3>
            @Scripts.Render("~/bundles/jquery")
            @Scripts.Render("~/bundles/bootstrap")
            @Scripts.Render("~/plugins/slimScroll")
            @Scripts.Render("~/bundles/inspinia")
            @Scripts.Render("~/bundles/modernizr")
            @Scripts.Render("~/bundles/eStream")
            @Scripts.Render("~/plugins/iCheck")
            <!-- Skin config script - only for demo purpose-->
            @Scripts.Render("~/bundles/skinConfig")

            @RenderSection("scripts", required: false)

            @RenderBody()
            <p class="m-t"> <small></small> </p>
        </div>
    </div>
    <script>
        $(document).on({
            ajaxStart: function () {
                $('#_AjaxLoading').modal('show');
            },
            ajaxStop: function () {
                $('#_AjaxLoading').modal('hide');
            }
        });
    </script>
</body>
</html>

eStream/Views/Shared/_Navigation.cshtml
@using eStream.Common.CommonClass
@using eStream.Helpers
@using eStream.Models
@{
    var user = SessionManager.GetUserInfoBO();
}
<nav class="navbar-default navbar-static-side" role="navigation">
    <div class="sidebar-collapse">
        <ul class="nav" id="side-menu">
            <li class="nav-header">
                <div class="dropdown profile-element">
                    <span>
                        @if (user.Avatar != null)
                        {
                            string imageBase64 = Convert.ToBase64String(user.Avatar);
                            string imageSrc = string.Format("data:image/jpg;base64,{0}", imageBase64);
                            <img src="@imageSrc" class="img-circle" width="48" height="48" />
                        }
                        else
                        {
                            <img src="~/Content/images/avatar-default.jpg" class="img-circle" width="48" height="48" />
                        }
                    </span>
                    <a data-toggle="dropdown" class="dropdown-toggle" href="#">
                        <span class="clear">
                            <span class="block m-t-xs">
                                <strong class="font-bold">@user.UserName</strong>
                            </span> <span class="text-muted text-xs block">@user.FullName <b class="caret"></b></span>
                        </span>
                    </a>
                    <ul class="dropdown-menu animated fadeInRight m-t-xs">
                        <li><a href="javascript:void(0)" data-toggle="modal" data-target="#modal-change-password" onclick="ChangePassPopup()"><i class="fa fa-user-circle-o"></i> Thông tin cá nhân</a></li>
                        <li role="separator" class="divider"></li>
                        <li><a href="@Url.Action("LogOut", "Home")">Đăng xuất</a></li>
                    </ul>
                </div>
                <div class="logo-element">
                    IN+
                </div>
            </li>
            @if (user.IsManager.GetValueOrDefault() == GlobalConstant.IS_ACTIVE || user.IsAdmin.GetValueOrDefault() == GlobalConstant.IS_ACTIVE)
            {
                <li><a href="@Url.Action("Index", "Control")"><i class="fa fa-calendar"></i> <span class="nav-label" data-i18n="nav.layouts">Chương trình phát</span></a></li>
            }
            <li><a href="@Url.Action("Index", "Manager")"><i class="fa fa-shield"></i> <span class="nav-label">Điều khiển thiết bị</span></a></li>
            <li><a href="@Url.Action("Index", "Fm")"><i class="fa fa-binoculars"></i> <span class="nav-label">Giám sát FM</span></a></li>
            @if (user.IsManager.GetValueOrDefault() == GlobalConstant.IS_ACTIVE || user.IsAdmin.GetValueOrDefault() == GlobalConstant.IS_ACTIVE)
            {
                <li class="list-inline" style="margin-left: 0px"><a id="aMenuLive" href="@Url.Action("Index", "Live")" style="display: inline-block;"><i class="fa fa-volume-up"></i> <span class="nav-label">Phát trực tiếp</span></a></li>
                <li class="active"><a href="javascript:void(0)"> <span class="nav-label" data-i18n="nav.layouts">Báo cáo</span></a> </li>
                <li><a href="@Url.Action("Index", "ReportTime")"><i class="fa fa-line-chart"></i> <span class="nav-label">Thời gian hoạt động</span></a></li>
                <li><a href="@Url.Action("Fm", "ReportTime")"><i class="fa fa-podcast"></i> <span class="nav-label">Thời gian phát FM</span></a></li>
            }
            @if (user.IsAdmin.GetValueOrDefault() == GlobalConstant.IS_ACTIVE)
            {
                <li class="active"><a href="javascript:void(0)"> <span class="nav-label" data-i18n="nav.layouts">Quản trị hệ thống</span></a> </li>
                <li><a href="@Url.Action("Index", "Device")"><i class="fa fa-microchip"></i> <span class="nav-label">Quản lý thiết bị</span></a></li>
                if (user.IsSupperAdmin.GetValueOrDefault() == GlobalConstant.IS_ACTIVE)
                {
                    <li><a href="@Url.Action("Index", "Channel")"><i class="fa fa-snowflake-o"></i> <span class="nav-label">Quản lý kênh</span></a></li>
                }
                <li><a href="@Url.Action("Index", "User")"><i class="fa fa-user"></i> <span class="nav-label" data-i18n="nav.layouts">Người dùng</span></a></li>
                <li><a href="@Url.Action("Index", "SendSmsHis")"><i class="fa fa-clock-o"></i> <span class="nav-label" data-i18n="nav.layouts">Lịch sử gửi SMS</span></a></li>
                if (user.IsSupperAdmin.GetValueOrDefault() == GlobalConstant.IS_ACTIVE ||
                    (user.IsAdmin.GetValueOrDefault() == GlobalConstant.IS_ACTIVE && user.UnitLevel == GlobalConstant.UNIT_TYPE_PROVINCE))
                {
                    <li><a href="@Url.Action("Index", "UnitManager")"><i class="fa fa-users"></i> <span class="nav-label">Đơn vị</span></a></li>
                    <li><a href="@Url.Action("Index", "Config")"><i class="fa fa-gear"></i> <span class="nav-label">Cấu hình</span></a></li>
                    <li><a href="@Url.Action("Index", "ActionLog")"><i class="fa fa-tasks"></i> <span class="nav-label">Giám sát hoạt động</span></a></li>
                }
            }
            <li><a href="~/help/index.html" target="_blank"><i class="fa fa-info-circle text-light-blue"></i><span class="text-light-blue">Hướng dẫn sử dụng</span></a></li>
        </ul>
    </div>
</nav>

eStream/Views/Shared/_TopNavbar.cshtml
@using eStream.Common.CommonClass
@{
    var user = SessionManager.GetUserInfoBO();
}

<div class="row border-bottom">
    <nav role="navigation" style="margin-bottom: 0">
        <div class="navbar-header">
            <a class="navbar-minimalize minimalize-styl-2 btn btn-primary " href="#"><i class="fa fa-bars"></i> </a>
            <form role="search" class="navbar-form-custom" method="post" action="">
                <div class="form-group">
					Hệ thống quản lý truyền thanh qua mạng Internet
                </div>
            </form>
        </div>
        <ul class="nav navbar-top-links navbar-right">
            <li>
                <a href="@Url.Action("LogOut", "Home")">
                    <i class="fa fa-sign-out"></i> Thoát
                </a>
            </li>
        </ul>
    </nav>
</div>
